name: 🐛 Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill in the information below to help us fix the issue.

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Please confirm that you've checked these items
      options:
        - label: I searched for similar issues and found no duplicates
          required: true
        - label: I'm using the latest version of the project
          required: true
        - label: I tested in a clean environment (incognito/guest)
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the problem
      placeholder: What happened that shouldn't have happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the problem
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what happened instead of the expected
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser did you encounter the problem in?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (specify in additional details)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Mobile (iOS)
        - Mobile (Android)
        - Other
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device did the problem occur on?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Errors
      description: If applicable, paste console logs or errors from browser
      placeholder: |
        Console logs, stack traces, or error messages
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos that help explain the problem
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information about the problem
      placeholder: |
        - Did this start happening recently?
        - Does it happen always or only sometimes?
        - Were you doing something specific when it happened?
        - Other relevant details
